### PR TITLE
Avoid to re-open dirvish buf

### PR DESCRIPTION
**Pull request by mattn**
```
$ vim .
```
and type some `<cr>` to open buf. but file is not opened.

### CODE REVIEW

**Comment by mattn** [comment]
I'm not sure this fix is right. should be checked `len(opend) > 0`?

**Comment by justinmk** [comment]
I'll check it out

**Comment by justinmk** [comment]
Problem seems to be that if a buffer such as `.` or `..` is created, any attempt to `:edit` a buffer with the fully-expanded name will instead re-route to the existing `.` or `..` buffer. To work around this, I `:bwipe` the `.` buffer, then try again with the fully-expanded path.

**Comment by mattn** [comment]
Seems not fixed yet? I get E16.

**Pull request closed without merging**
