### PR TITLE
Add plug to allow overriding global `-` mapping.

### PR DESCRIPTION
**Pull request by lifepillar**
I'd rather have my own mapping for opening Dirvish rather than overriding `-`.

### CODE REVIEW

**Comment by hauleth** [comment]
I have my own mappings:

```
if mapcheck('+', 'n') ==# ''
  nnoremap <silent> + :<C-U>exe 'Dirvish %:p'.repeat(':h',v:count1)<CR>
endif
if mapcheck('-', 'n') ==# ''
  nnoremap <silent> - :<C-U>Dirvish<CR>
endif
```

**Comment by lifepillar** [comment]
The point is that I don't want `-` to be overridden by the plugin.

**Comment by justinmk** [comment]
Merged, thanks. Mapping is `<Plug>(dirvish_up)`, and it will be used globally as well as in dirvish buffers.

**Comment by lifepillar** [comment]
Thanks! In fact, buffer-local `-` is perfectly fine for me. It's only the global mapping that bothers me, because (1) I am used to type `-` to move up, and (2) for specific filetypes (outlines) I override `-` to do smarter jumps (to parent). If Dirvish maps `-` globally, I cannot do (1) any longer and I cannot open Dirvish from buffers of type (2) using `-`.

I understand your (and tpope's) point of view (you jump from the file up to its directory, then up again and again, so it's one action => one mapping), and as a default it's ok, but I think that allowing the user to set the global and buffer-local mappings independently provides more flexibility.

**Comment by justinmk** [comment]
@lifepillar Since it re-uses your global `<Plug>(dirvish_up)` map for the buffer-local, you will need to override the buffer-local with something like:

au FileType dirvish nmap <buffer> - <Plug>(dirvish_up)

**Comment by lifepillar** [comment]
Fair enough. Thanks again!

**Comment by nomasprime** [comment]
@justinmk to avoid duplication, is overriding the global map with a buffer map to `Nop` the best way to disable it?

```viml
nmap <silent> <Leader>e <Plug>(dirvish_up)

augroup dirvish_config
  autocmd!
  autocmd FileType dirvish nmap <buffer> <Leader>e <Nop>
  autocmd FileType dirvish nmap <buffer> - <Plug>(dirvish_up)
  ...
```

AFAIK doing something like `autocmd FileType dirvish silent! unmap <buffer> <Leader>e` would just unmap any existing matching buffer map, ie, re-expose the global map.

**Pull request closed without merging**
