### PR TITLE
Enable directory name completion for :Dirvish

### PR DESCRIPTION
**Pull request by noahfrederick**

### CODE REVIEW

**Comment by justinmk** [comment]
Sadly this doesn't play well with 

     Dirvish %

Any ideas?

**Comment by noahfrederick** [comment]
I'm probably overlooking something obvious, but in what way doesn't it play well?

**Comment by justinmk** [comment]
I'm not at a computer, but last time I tried it, it errored. Does it not?

**Comment by noahfrederick** [comment]
I can't make it error in a mapping or not. The completion only comes into play when sending `'wildchar'`. It doesn't police the command's argument(s), nor should a built-in completion function ever throw an error. The following all work as expected for me:

```vim
:Dirvish %<CR>                            " Open directory viewer at %:p:h
:Dirvish %<Tab>     --> :Dirvish %        " No completions--nothing happens
:Dirvish fo<Tab>    --> :Dirvish foo/     " Expands extant directory foo/
:Dirvish foo/b<Tab> --> :Dirvish foo/bar/ " Expands extant subdirectories
```

**Comment by justinmk** [comment]
Only case that seems to be a problem is if the current file doesn't have a name. E.g.:

```
:enew
:Dirvish %
E499: Empty file name for '%' or '#', only works with ":p:h" 
```

On the other hand there is no alternative for users who want directory-only completion at the command line (I think?), so I'll just recommendi `:Dirvish %:p:h` for the mapping to work around the empty-file edge case.

**Comment by noahfrederick** [comment]
> Only case that seems to be a problem is if the current file doesn't have a name.

Huh. Can't say I understand why the completion type affects anything besides completion. That's too bad.

> On the other hand there is no alternative for users who want directory-only completion at the command line (I think?),

Could reimplement directory completion with a custom completion function, but it probably isn't worth the trouble.

**Pull request merged**
