### PR TITLE
Use prompter if possible

### PR DESCRIPTION
**Pull request by mattn**
We can remove trailing `\ze[^\/]*[\/]\=$`

### CODE REVIEW

**Comment by mattn** [comment]
Ah, it's better not use `\<C-G>`. please wait.

**Comment by justinmk** [comment]
Thanks, but this is a lot of code for what I guess is just a cosmetic effect? If the user presses `<up>` in the prompt, will it show previous searches? 

My experience with [vim-over](https://github.com/osyo-manga/vim-over) makes me very wary of trying to mimic the built-in command line.

However, maybe others can use this PR if they want.

**Comment by mattn** [comment]
vital is bits over-spec for dirvish. if you want, you can copy my codes into your's.

**Comment by mattn** [comment]
Updated to support history with cursor up/down.

**Comment by mattn** [comment]
I could setup `/` to replace behavior to use my prompter.

```vim
nmap <Plug>(nomap-dirvish_up) <Plug>(dirvish_up)
augroup DirVish
  autocmd FileType dirvish :call s:setup_dirvish()
augroup END

function! s:setup_dirvish()
  nunmap <buffer> /

  call prompter#ready()
  nnoremap <buffer> / :<c-u>call <SID>search('/')<CR>
  nnoremap <buffer> ? :<c-u>call <SID>search('?')<CR>
endfunction

function! s:search(dir)
  let s:dir = a:dir
  let s:pos = getpos('.')
  call prompter#input({
  \ 'prompt': a:dir,
  \ 'prompt_color': 'Normal',
  \ 'cursor': '_',
  \ 'cursor_color': 'StatusLine',
  \ 'histtype': '/',
  \ 'on_change': function('<SID>on_change'),
  \ 'on_enter': function('<SID>on_enter'),
  \ 'on_cancel': function('<SID>on_cancel'),
  \ })
endfunction

function! s:on_cancel(input)
  call setpos('.', s:pos)
endfunction

function! s:on_enter(input)
  let @/ = join(a:input, '') . '\ze[^\/]*[\/]\=$'
endfunction

function! s:on_change(input)
  call setpos('.', s:pos)
  call search(join(a:input, '') . '\ze[^\/]*[\/]\=$', s:dir == '/' ? '' : 'bw')
  normal! 0
endfunction
```

**Pull request closed without merging**
